---
title: "overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
 
```{r setup}
library(evaluationDB)
library(tidyverse)

state_boxplot <- function(state){
  
df<-evaluationDB %>% 
  filter(state == !!state) %>% 
  select(year, district_name, percent_level1, percent_level2, percent_level3, percent_level4) %>% 
  pivot_longer(cols = c(percent_level1, percent_level2, percent_level3, percent_level4), names_to = "level", values_to = "percent")

ggplot(df, aes(y = percent, fill = level)) +
                 geom_boxplot() +
  facet_wrap("year") + 
  theme(legend.position="bottom")
}

state_graph <- function(state){
  state_boxplot(state)
}

```

## Connecticut
```{r, CT}
state_graph("CT")
```

## Florida
```{r, FL}
state_graph("FL")
```

## Idaho
```{r, ID}
state_graph("ID")
```

## Indiana
```{r, IN}
state_graph("IN")
```

## Louisiana
```{r, LA}
state_graph("LA")
```

## Massachussetts
```{r, MA}
state_graph("MA")
```

## Michigan
```{r, MI}
state_graph("MI")
```

## New Jersey
```{r, NJ}
state_graph("NJ")
```

## New York
```{r, NY}
state_graph("NY")
```

## Ohio
```{r, OH}
state_graph("OH")
```

## Rhode Island
```{r, RI}
state_graph("RI")
```


# TO DO

This vignette will describe the data, why its important

- Which states are included
- state*years and n-districts per state-year
- some simple descriptives?
- notes about things to be aware of?
- link to github for issues
